"""Add more features to home

Revision ID: 112d5ea8246f
Revises: 08386ca6e549
Create Date: 2024-04-25 16:23:16.718548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '112d5ea8246f'
down_revision = '08386ca6e549'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('homes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bathrooms', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('garages', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('bedrooms', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('area', sa.String(length=255), nullable=True))
        batch_op.drop_column('size')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('homes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('area')
        batch_op.drop_column('bedrooms')
        batch_op.drop_column('garages')
        batch_op.drop_column('bathrooms')

    # ### end Alembic commands ###
