"""Add meeting

Revision ID: 8db29b51f54d
Revises: 95979d057d0a
Create Date: 2023-07-13 17:42:33.853941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8db29b51f54d'
down_revision = '95979d057d0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('invitor_id', sa.Integer(), nullable=True),
    sa.Column('invited_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', name='meetingstatustype'), nullable=False),
    sa.ForeignKeyConstraint(['invited_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invitor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meetings')
    # ### end Alembic commands ###
