"""Add visitations

Revision ID: b8939dc50d21
Revises: b0664875d44e
Create Date: 2023-07-13 14:59:02.063662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8939dc50d21'
down_revision = 'b0664875d44e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_hour', sa.DateTime(), nullable=False),
    sa.Column('end_hour', sa.DateTime(), nullable=False),
    sa.Column('organizator_id', sa.Integer(), nullable=True),
    sa.Column('home_id', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['home_id'], ['homes.id'], ),
    sa.ForeignKeyConstraint(['organizator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visitations')
    # ### end Alembic commands ###
