"""Add home and land to meetings

Revision ID: e441df4c38a7
Revises: 8db29b51f54d
Create Date: 2023-07-18 12:09:09.737614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e441df4c38a7'
down_revision = '8db29b51f54d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('land_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'lands', ['land_id'], ['id'])
        batch_op.create_foreign_key(None, 'homes', ['home_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('land_id')
        batch_op.drop_column('home_id')

    # ### end Alembic commands ###
